Earth Bender:
https://www.roblox.com/catalog/4367486993/Anime-School-Girl
https://www.roblox.com/catalog/63690008/Pal-Hair
Star Glicther:
https://www.roblox.com/catalog/63690008/Pal-Hair
https://www.roblox.com/catalog/48474294/ROBLOX-Girl-Hair
https://www.roblox.com/catalog/451220849/Lavender-Updo
https://www.roblox.com/catalog/62234425/Brown-Hair
https://www.roblox.com/catalog/48474313/Red-Roblox-Cap
Simple Car:
https://www.roblox.com/catalog/4821679391/R-Wagon
Extendo V1:

**ΝΟΤΕ: You need to wear pants and a shirt. Not a specific one, wear whatever you want, it just needs to be a shirt and pants.**

https://www.roblox.com/catalog/451220849/Lavender-Updo
https://www.roblox.com/catalog/63690008/Pal-Hair
https://www.roblox.com/catalog/48474294/ROBLOX-Girl-Hair
https://www.roblox.com/catalog/62234425/Brown-Hair
Ghost:
https://www.roblox.com/catalog/5702357673/GHOST
Hammer:
https://www.roblox.com/catalog/4739580137/Oversized-Hammer-of-the-Titans
Sans:
https://www.roblox.com/catalog/4107751917/Bone-Antlers
Super-Man:
https://www.roblox.com/catalog/4820288389/Red-Cape
Telekinisis Gun:
https://www.roblox.com/catalog/3033910400/International-Fedora-Germany
https://www.roblox.com/catalog/4933294084/Type-37-Pulse-Rifle
Uxie:
https://www.roblox.com/catalog/63690008/Pal-Hair
https://www.roblox.com/catalog/48474294/ROBLOX-Girl-Hair
https://www.roblox.com/catalog/451220849/Lavender-Updo
https://www.roblox.com/catalog/62234425/Brown-Hair
https://www.roblox.com/catalog/48474313/Red-Roblox-Cap
Wings:
https://www.roblox.com/catalog/5593848751/The-Right-Solo-Wing
https://www.roblox.com/catalog/5505301521/The-Left-Solo-Wing
Zen God:
https://www.roblox.com/catalog/4876469013/Destructive-Aura
https://www.roblox.com/catalog/4880921571/Corrupt-Aura
https://www.roblox.com/catalog/5703072943/Orbs-of-Honesty
